version: "3"
name: "erisa-paycore-prod"
services:
  app:
    env_file: ".env.prod"
    image: 'erisa/paycore-prod'
    build:
      context: .
    restart: always
    networks:
      traefik_net:
        aliases:
          - paycore.erisa
      mongoCluster:
    environment:
      - SUCCESS_URL_CREATE=https://dashboard.erisa.space/create/place/success
    labels:
      - traefik.enable=true
      - traefik.http.routers.paycore-erisa-prod.entrypoints=https
      - traefik.http.routers.paycore-erisa-prod.rule=Host(`paycore.erisa.space`)
      - traefik.http.routers.paycore-erisa-prod.tls=true
      - traefik.http.routers.paycore-erisa-prod.tls.certresolver=letsEncrypt
      - traefik.http.services.paycore-erisa-prod.loadbalancer.server.port=4000


networks:
  traefik_net:
    external: true
  mongoCluster:
    external: true
