version: "3"
name: "erisa-paycore-dev1"
services:
  app:
    env_file: ".env.dev1"
    image: 'erisa/paycore-dev1'
    build:
      context: .
    restart: always
    networks:
      traefik_net:
        aliases:
          - paycore.dev1.erisa
    environment:
      - SUCCESS_URL_CREATE=https://dashboard.dev1.erisa.space/create/place/success
    labels:
      - traefik.enable=true
      - traefik.http.routers.paycore-erisa-dev1.entrypoints=https
      - traefik.http.routers.paycore-erisa-dev1.rule=Host(`paycore.dev1.erisa.space`)
      - traefik.http.routers.paycore-erisa-dev1.tls=true
      - traefik.http.routers.paycore-erisa-dev1.tls.certresolver=letsEncrypt
      - traefik.http.services.paycore-erisa-dev1.loadbalancer.server.port=4000


networks:
  traefik_net:
    external: true
